services:
  cache1:
    build: .
    ports:
      - "9527:8080"
    environment:
      - NODE_ID=0
      - NODE_PORT=8080
      - CLUSTER_NODES=cache1:8080,cache2:8080,cache3:8080

  cache2:
    build: .
    ports:
      - "9528:8080"
    environment:
      - NODE_ID=1
      - NODE_PORT=8080
      - CLUSTER_NODES=cache1:8080,cache2:8080,cache3:8080

  cache3:
    build: .
    ports:
      - "9529:8080"
    environment:
      - NODE_ID=2
      - NODE_PORT=8080
      - CLUSTER_NODES=cache1:8080,cache2:8080,cache3:8080

